<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="AuthProvider.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.ViewFeatures" Version="2.3.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Localization.Abstractions" Version="10.0.1" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resource\Message.Designer.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Message.Designer.resx</DependentUpon>
    </Compile>
    <Compile Update="Resource\Title.Designer.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Title.Designer.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resource\Message.Designer.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resource\Message.Designer.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Message.Designer.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resource\Title.Designer.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resource\Title.Designer.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Title.Designer.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
