// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

namespace Repository.Migrations
{
    [DbContext(typeof(OrgContext))]
    [Migration("20210602210933_CreatePreferenceTable")]
    partial class CreatePreferenceTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Entity.Model.Branch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<bool>("Hide")
                        .HasColumnType("bit");

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaskText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Branch");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Hide = false,
                            Name = "Main Branch",
                            ParentId = 0L,
                            Status = 0,
                            TypeId = 0L
                        });
                });

            modelBuilder.Entity("Entity.Model.Classification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<bool>("BeManufactured")
                        .HasColumnType("bit");

                    b.Property<bool>("BePurchased")
                        .HasColumnType("bit");

                    b.Property<bool>("BeSold")
                        .HasColumnType("bit");

                    b.Property<bool>("Hide")
                        .HasColumnType("bit");

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaskText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Classification");
                });

            modelBuilder.Entity("Entity.Model.Dealer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long>("CodeNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Hide")
                        .HasColumnType("bit");

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaskText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Phone")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Dealer");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "1",
                            CodeNumber = 1L,
                            Hide = false,
                            Name = "Unspecified",
                            ParentId = 0L,
                            Status = 0,
                            TypeId = 1L
                        });
                });

            modelBuilder.Entity("Entity.Model.Invoice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CodeNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<long>("DealerId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DiscountType")
                        .HasColumnType("int");

                    b.Property<bool>("Hide")
                        .HasColumnType("bit");

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaskText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Net")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Paid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long>("PaymentTypeId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Remaining")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Service")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ServiceType")
                        .HasColumnType("int");

                    b.Property<long?>("ShiftId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TaxType")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PaymentTypeId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("StoreId");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("Entity.Model.InvoiceProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Hide")
                        .HasColumnType("bit");

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint");

                    b.Property<string>("MaskText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Net")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("RowNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("UnitId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StoreId");

                    b.HasIndex("UnitId");

                    b.ToTable("InvoiceProduct");
                });

            modelBuilder.Entity("Entity.Model.InvoiceType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<bool>("Hide")
                        .HasColumnType("bit");

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InOut")
                        .HasColumnType("int");

                    b.Property<string>("MaskText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("InvoiceType");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Hide = false,
                            InOut = -1,
                            Name = "Sales",
                            ParentId = 0L,
                            Status = 0,
                            TypeId = 0L
                        },
                        new
                        {
                            Id = 2L,
                            Hide = false,
                            InOut = 1,
                            Name = "Purchase",
                            ParentId = 0L,
                            Status = 0,
                            TypeId = 0L
                        },
                        new
                        {
                            Id = 3L,
                            Hide = false,
                            InOut = 1,
                            Name = "Return Sales",
                            ParentId = 0L,
                            Status = 0,
                            TypeId = 0L
                        },
                        new
                        {
                            Id = 4L,
                            Hide = false,
                            InOut = -1,
                            Name = "Return Purchase",
                            ParentId = 0L,
                            Status = 0,
                            TypeId = 0L
                        });
                });

            modelBuilder.Entity("Entity.Model.LogSys", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<long>("EstimateBySecond")
                        .HasColumnType("bigint");

                    b.Property<bool>("Hide")
                        .HasColumnType("bit");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LogAccessLevel")
                        .HasColumnType("int");

                    b.Property<int>("LogStatus")
                        .HasColumnType("int");

                    b.Property<int>("LogType")
                        .HasColumnType("int");

                    b.Property<string>("MaskText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResourceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResourceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScreenName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Sent")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("LogSys");
                });

            modelBuilder.Entity("Entity.Model.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CodeNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<long>("DealerId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Hide")
                        .HasColumnType("bit");

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaskText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Net")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TableId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Entity.Model.OrderProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Hide")
                        .HasColumnType("bit");

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaskText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Net")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("RowNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("UnitId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UnitId");

                    b.ToTable("OrderProduct");
                });

            modelBuilder.Entity("Entity.Model.PaymentType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<bool>("Hide")
                        .HasColumnType("bit");

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaskText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("PaymentType");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Hide = false,
                            Name = "Cash",
                            ParentId = 0L,
                            Status = 0,
                            TypeId = 0L
                        },
                        new
                        {
                            Id = 2L,
                            Hide = false,
                            Name = "Check",
                            ParentId = 0L,
                            Status = 0,
                            TypeId = 0L
                        });
                });

            modelBuilder.Entity("Entity.Model.Permission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<bool>("Hide")
                        .HasColumnType("bit");

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaskText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permission");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Hide = false,
                            Key = "AllPage",
                            ParentId = 0L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "AllPage.All"
                        },
                        new
                        {
                            Id = 10L,
                            Hide = false,
                            Key = "Setting",
                            ParentId = 1L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Setting.All"
                        },
                        new
                        {
                            Id = 101L,
                            Hide = false,
                            Key = "Branchs",
                            ParentId = 10L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Branchs.All"
                        },
                        new
                        {
                            Id = 10101L,
                            Hide = false,
                            Key = "View",
                            ParentId = 101L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Branchs.View"
                        },
                        new
                        {
                            Id = 10102L,
                            Hide = false,
                            Key = "Add",
                            ParentId = 101L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Branchs.Add"
                        },
                        new
                        {
                            Id = 10103L,
                            Hide = false,
                            Key = "Edit",
                            ParentId = 101L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Branchs.Edit"
                        },
                        new
                        {
                            Id = 10104L,
                            Hide = false,
                            Key = "Delete",
                            ParentId = 101L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Branchs.Delete"
                        },
                        new
                        {
                            Id = 102L,
                            Hide = false,
                            Key = "Roles",
                            ParentId = 10L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Roles.All"
                        },
                        new
                        {
                            Id = 10201L,
                            Hide = false,
                            Key = "View",
                            ParentId = 102L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Roles.View"
                        },
                        new
                        {
                            Id = 10202L,
                            Hide = false,
                            Key = "Add",
                            ParentId = 102L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Roles.Add"
                        },
                        new
                        {
                            Id = 10203L,
                            Hide = false,
                            Key = "Edit",
                            ParentId = 102L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Roles.Edit"
                        },
                        new
                        {
                            Id = 10204L,
                            Hide = false,
                            Key = "Delete",
                            ParentId = 102L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Roles.Delete"
                        },
                        new
                        {
                            Id = 103L,
                            Hide = false,
                            Key = "Users",
                            ParentId = 10L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Users.All"
                        },
                        new
                        {
                            Id = 10301L,
                            Hide = false,
                            Key = "View",
                            ParentId = 103L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Users.View"
                        },
                        new
                        {
                            Id = 10302L,
                            Hide = false,
                            Key = "Add",
                            ParentId = 103L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Users.Add"
                        },
                        new
                        {
                            Id = 10303L,
                            Hide = false,
                            Key = "Edit",
                            ParentId = 103L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Users.Edit"
                        },
                        new
                        {
                            Id = 10304L,
                            Hide = false,
                            Key = "Delete",
                            ParentId = 103L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Users.Delete"
                        },
                        new
                        {
                            Id = 104L,
                            Hide = false,
                            Key = "Shifts",
                            ParentId = 10L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Shifts.All"
                        },
                        new
                        {
                            Id = 10401L,
                            Hide = false,
                            Key = "View",
                            ParentId = 104L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Shifts.View"
                        },
                        new
                        {
                            Id = 10402L,
                            Hide = false,
                            Key = "Add",
                            ParentId = 104L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Shifts.Add"
                        },
                        new
                        {
                            Id = 10403L,
                            Hide = false,
                            Key = "Edit",
                            ParentId = 104L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Shifts.Edit"
                        },
                        new
                        {
                            Id = 10404L,
                            Hide = false,
                            Key = "Delete",
                            ParentId = 104L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Shifts.Delete"
                        },
                        new
                        {
                            Id = 20L,
                            Hide = false,
                            Key = "Sales",
                            ParentId = 1L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Sales.All"
                        },
                        new
                        {
                            Id = 201L,
                            Hide = false,
                            Key = "Products",
                            ParentId = 20L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Products.All"
                        },
                        new
                        {
                            Id = 20101L,
                            Hide = false,
                            Key = "View",
                            ParentId = 201L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Products.View"
                        },
                        new
                        {
                            Id = 20102L,
                            Hide = false,
                            Key = "Add",
                            ParentId = 201L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Products.Add"
                        },
                        new
                        {
                            Id = 20103L,
                            Hide = false,
                            Key = "Edit",
                            ParentId = 201L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Products.Edit"
                        },
                        new
                        {
                            Id = 20104L,
                            Hide = false,
                            Key = "Delete",
                            ParentId = 201L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Products.Delete"
                        },
                        new
                        {
                            Id = 202L,
                            Hide = false,
                            Key = "Classifications",
                            ParentId = 20L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Classifications.All"
                        },
                        new
                        {
                            Id = 20201L,
                            Hide = false,
                            Key = "View",
                            ParentId = 202L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Classifications.View"
                        },
                        new
                        {
                            Id = 20202L,
                            Hide = false,
                            Key = "Add",
                            ParentId = 202L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Classifications.Add"
                        },
                        new
                        {
                            Id = 20203L,
                            Hide = false,
                            Key = "Edit",
                            ParentId = 202L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Classifications.Edit"
                        },
                        new
                        {
                            Id = 20204L,
                            Hide = false,
                            Key = "Delete",
                            ParentId = 202L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Classifications.Delete"
                        },
                        new
                        {
                            Id = 203L,
                            Hide = false,
                            Key = "UnitsMeasure",
                            ParentId = 20L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "UnitsMeasure.All"
                        },
                        new
                        {
                            Id = 20301L,
                            Hide = false,
                            Key = "View",
                            ParentId = 203L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "UnitsMeasure.View"
                        },
                        new
                        {
                            Id = 20302L,
                            Hide = false,
                            Key = "Add",
                            ParentId = 203L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "UnitsMeasure.Add"
                        },
                        new
                        {
                            Id = 20303L,
                            Hide = false,
                            Key = "Edit",
                            ParentId = 203L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "UnitsMeasure.Edit"
                        },
                        new
                        {
                            Id = 20304L,
                            Hide = false,
                            Key = "Delete",
                            ParentId = 203L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "UnitsMeasure.Delete"
                        },
                        new
                        {
                            Id = 204L,
                            Hide = false,
                            Key = "Clients",
                            ParentId = 20L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Clients.All"
                        },
                        new
                        {
                            Id = 20401L,
                            Hide = false,
                            Key = "View",
                            ParentId = 204L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Clients.View"
                        },
                        new
                        {
                            Id = 20402L,
                            Hide = false,
                            Key = "Add",
                            ParentId = 204L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Clients.Add"
                        },
                        new
                        {
                            Id = 20403L,
                            Hide = false,
                            Key = "Edit",
                            ParentId = 204L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Clients.Edit"
                        },
                        new
                        {
                            Id = 20404L,
                            Hide = false,
                            Key = "Delete",
                            ParentId = 204L,
                            Status = 0,
                            TypeId = 0L,
                            Value = "Clients.Delete"
                        });
                });

            modelBuilder.Entity("Entity.Model.Preference", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<bool>("Hide")
                        .HasColumnType("bit");

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaskText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Preference");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Hide = false,
                            Key = "DefaultStore",
                            ParentId = 0L,
                            Reference = "Invoice",
                            Status = 0,
                            TypeId = 1L,
                            Value = "1"
                        },
                        new
                        {
                            Id = 2L,
                            Hide = false,
                            Key = "DefaultCustomer",
                            ParentId = 0L,
                            Reference = "Invoice",
                            Status = 0,
                            TypeId = 1L,
                            Value = "1"
                        },
                        new
                        {
                            Id = 3L,
                            Hide = false,
                            Key = "DefaultPaymentType",
                            ParentId = 0L,
                            Reference = "Invoice",
                            Status = 0,
                            TypeId = 1L,
                            Value = "1"
                        },
                        new
                        {
                            Id = 4L,
                            Hide = false,
                            Key = "DiscountValue",
                            ParentId = 0L,
                            Reference = "Invoice",
                            Status = 0,
                            TypeId = 1L,
                            Value = ""
                        },
                        new
                        {
                            Id = 5L,
                            Hide = false,
                            Key = "DefaultDiscountType",
                            ParentId = 0L,
                            Reference = "Invoice",
                            Status = 0,
                            TypeId = 1L,
                            Value = "2"
                        },
                        new
                        {
                            Id = 6L,
                            Hide = false,
                            Key = "ServiceValue",
                            ParentId = 0L,
                            Reference = "Invoice",
                            Status = 0,
                            TypeId = 1L,
                            Value = ""
                        },
                        new
                        {
                            Id = 7L,
                            Hide = false,
                            Key = "DefaultServiceType",
                            ParentId = 0L,
                            Reference = "Invoice",
                            Status = 0,
                            TypeId = 1L,
                            Value = "2"
                        },
                        new
                        {
                            Id = 8L,
                            Hide = false,
                            Key = "TaxValue",
                            ParentId = 0L,
                            Reference = "Invoice",
                            Status = 0,
                            TypeId = 1L,
                            Value = "14"
                        },
                        new
                        {
                            Id = 9L,
                            Hide = false,
                            Key = "DefaultTaxType",
                            ParentId = 0L,
                            Reference = "Invoice",
                            Status = 0,
                            TypeId = 1L,
                            Value = "2"
                        },
                        new
                        {
                            Id = 10L,
                            Hide = false,
                            Key = "NumberLine",
                            ParentId = 0L,
                            Reference = "Invoice",
                            Status = 0,
                            TypeId = 1L,
                            Value = "6"
                        },
                        new
                        {
                            Id = 11L,
                            Hide = false,
                            Key = "OrderTabe",
                            ParentId = 0L,
                            Reference = "Invoice",
                            Status = 0,
                            TypeId = 1L,
                            Value = "1"
                        },
                        new
                        {
                            Id = 12L,
                            Hide = false,
                            Key = "AutoSave",
                            ParentId = 0L,
                            Reference = "Invoice",
                            Status = 0,
                            TypeId = 1L,
                            Value = "0"
                        });
                });

            modelBuilder.Entity("Entity.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<long>("ClassificationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long>("CodeNumber")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("DealerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Hide")
                        .HasColumnType("bit");

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaskText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nickname")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Recipe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClassificationId");

                    b.HasIndex("DealerId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Entity.Model.ProductPropertyElement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<bool>("Hide")
                        .HasColumnType("bit");

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("bit");

                    b.Property<string>("MaskText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long>("PropertyElementId")
                        .HasColumnType("bigint");

                    b.Property<long>("PropertyId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PropertyElementId");

                    b.HasIndex("PropertyId");

                    b.ToTable("ProductPropertyElement");
                });

            modelBuilder.Entity("Entity.Model.ProductRecipe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<bool>("Hide")
                        .HasColumnType("bit");

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaskText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("RecipeId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("UnitId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductRecipe");
                });

            modelBuilder.Entity("Entity.Model.ProductUnit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<bool>("DefaultUnit")
                        .HasColumnType("bit");

                    b.Property<bool>("Hide")
                        .HasColumnType("bit");

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaskText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("UnitId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UnitId");

                    b.ToTable("ProductUnit");
                });

            modelBuilder.Entity("Entity.Model.Property", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<bool>("Hide")
                        .HasColumnType("bit");

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaskText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Property");
                });

            modelBuilder.Entity("Entity.Model.PropertyElement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<bool>("Hide")
                        .HasColumnType("bit");

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaskText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long>("PropertyId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyElement");
                });

            modelBuilder.Entity("Entity.Model.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<bool>("Hide")
                        .HasColumnType("bit");

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaskText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Hide = false,
                            Name = "Owner",
                            ParentId = 0L,
                            Status = 0,
                            TypeId = 0L
                        });
                });

            modelBuilder.Entity("Entity.Model.Shift", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<bool>("Hide")
                        .HasColumnType("bit");

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaskText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Shift");
                });

            modelBuilder.Entity("Entity.Model.Store", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Hide")
                        .HasColumnType("bit");

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaskText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("Store");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BranchId = 1L,
                            Hide = false,
                            Name = "Main Store",
                            ParentId = 0L,
                            Status = 0,
                            TypeId = 0L
                        });
                });

            modelBuilder.Entity("Entity.Model.Unit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<bool>("Hide")
                        .HasColumnType("bit");

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaskText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Unit");
                });

            modelBuilder.Entity("Entity.Model.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long?>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Hide")
                        .HasColumnType("bit");

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaskText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("RoleId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Hide = false,
                            Name = "Owner",
                            ParentId = 0L,
                            Password = "iebLM3YfOZ4fcXYL1jInxA==",
                            RoleId = 1L,
                            Status = 0,
                            TypeId = 0L,
                            UserName = "Owner"
                        });
                });

            modelBuilder.Entity("Entity.Model.Invoice", b =>
                {
                    b.HasOne("Entity.Model.Dealer", "Dealer")
                        .WithMany()
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Model.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");

                    b.HasOne("Entity.Model.PaymentType", "PaymentType")
                        .WithMany()
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Model.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId");

                    b.HasOne("Entity.Model.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealer");

                    b.Navigation("Order");

                    b.Navigation("PaymentType");

                    b.Navigation("Shift");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Entity.Model.InvoiceProduct", b =>
                {
                    b.HasOne("Entity.Model.Invoice", "Invoice")
                        .WithMany("InvoiceProducts")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Model.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Model.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Product");

                    b.Navigation("Store");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Entity.Model.Order", b =>
                {
                    b.HasOne("Entity.Model.Dealer", "Dealer")
                        .WithMany()
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealer");
                });

            modelBuilder.Entity("Entity.Model.OrderProduct", b =>
                {
                    b.HasOne("Entity.Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Model.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Entity.Model.Product", b =>
                {
                    b.HasOne("Entity.Model.Classification", "Classification")
                        .WithMany()
                        .HasForeignKey("ClassificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Model.Dealer", "Dealer")
                        .WithMany()
                        .HasForeignKey("DealerId");

                    b.Navigation("Classification");

                    b.Navigation("Dealer");
                });

            modelBuilder.Entity("Entity.Model.ProductPropertyElement", b =>
                {
                    b.HasOne("Entity.Model.Product", "Product")
                        .WithMany("ProductPropertyElements")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Model.PropertyElement", "PropertyElement")
                        .WithMany()
                        .HasForeignKey("PropertyElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Model.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Property");

                    b.Navigation("PropertyElement");
                });

            modelBuilder.Entity("Entity.Model.ProductRecipe", b =>
                {
                    b.HasOne("Entity.Model.Product", null)
                        .WithMany("ProductRecipes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entity.Model.ProductUnit", b =>
                {
                    b.HasOne("Entity.Model.Product", "Product")
                        .WithMany("ProductUnits")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Model.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Entity.Model.PropertyElement", b =>
                {
                    b.HasOne("Entity.Model.Property", "Property")
                        .WithMany("propertyElements")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Entity.Model.Store", b =>
                {
                    b.HasOne("Entity.Model.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Entity.Model.User", b =>
                {
                    b.HasOne("Entity.Model.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId");

                    b.HasOne("Entity.Model.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Entity.Model.Invoice", b =>
                {
                    b.Navigation("InvoiceProducts");
                });

            modelBuilder.Entity("Entity.Model.Product", b =>
                {
                    b.Navigation("ProductPropertyElements");

                    b.Navigation("ProductRecipes");

                    b.Navigation("ProductUnits");
                });

            modelBuilder.Entity("Entity.Model.Property", b =>
                {
                    b.Navigation("propertyElements");
                });
#pragma warning restore 612, 618
        }
    }
}
