<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Reporting.Application/Reporting.Application.csproj" />
    <ProjectReference Include="../../CommercialDocuments/CommercialDocuments.Domain/CommercialDocuments.Domain.csproj" />
    <ProjectReference Include="../../Treasury/Treasury.Domain/Treasury.Domain.csproj" />
    <ProjectReference Include="../../Inventory/Inventory.Domain/Inventory.Domain.csproj" />
    <ProjectReference Include="../../Parties/Parties.Domain/Parties.Domain.csproj" />
    <ProjectReference Include="../../Catalog/Catalog.Domain/Catalog.Domain.csproj" />
    <ProjectReference Include="../../MasterData/MasterData.Domain/MasterData.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
  </ItemGroup>

</Project>
