<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Contracts\**" />
    <Compile Remove="Features\**" />
    <Compile Remove="Profiles\**" />
    <EmbeddedResource Remove="Contracts\**" />
    <EmbeddedResource Remove="Features\**" />
    <EmbeddedResource Remove="Profiles\**" />
    <None Remove="Contracts\**" />
    <None Remove="Features\**" />
    <None Remove="Profiles\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="MediatR" Version="13.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\Entity\Entity.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Commands\Admin\" />
    <Folder Include="DTOs\" />
    <Folder Include="Queries\Admin\" />
    <Folder Include="Queries\Org\" />
    <Folder Include="Validators\" />
  </ItemGroup>

</Project>
