<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Contracts\**" />
    <Compile Remove="Features\**" />
    <Compile Remove="Profiles\**" />
    <EmbeddedResource Remove="Contracts\**" />
    <EmbeddedResource Remove="Features\**" />
    <EmbeddedResource Remove="Profiles\**" />
    <None Remove="Contracts\**" />
    <None Remove="Features\**" />
    <None Remove="Profiles\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\" />
    <Folder Include="DTOs\" />
    <Folder Include="Commands\" />
    <Folder Include="Queries\" />
    <Folder Include="Validators\" />
  </ItemGroup>

</Project>
