<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Entities\AdminDb\**" />
    <Compile Remove="Entities\OrgDb\**" />
    <EmbeddedResource Remove="Entities\AdminDb\**" />
    <EmbeddedResource Remove="Entities\OrgDb\**" />
    <None Remove="Entities\AdminDb\**" />
    <None Remove="Entities\OrgDb\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Abstraction\IAdminContext.cs" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Aggregate\" />
    <Folder Include="Entities\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Events\" />
    <Folder Include="Exceptions\" />
    <Folder Include="ValueObjects\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="CorePagination" Version="0.6.0" />
    <PackageReference Include="MediatR" Version="14.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Entity\Entity.csproj" />
    <ProjectReference Include="..\Utility\Utility.csproj" />
  </ItemGroup>

</Project>
