<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../BuildingBlocks/OrgSys.SharedKernel/OrgSys.SharedKernel.csproj" />
    <ProjectReference Include="../../MasterData/MasterData.Domain/MasterData.Domain.csproj" />
    <ProjectReference Include="../../Organization/Organization.Domain/Organization.Domain.csproj" />
    <ProjectReference Include="../../Accounting/Accounting.Domain/Accounting.Domain.csproj" />
  </ItemGroup>

</Project>
