<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="BAL\Data\AccountsType\AccountTypeService.cs" />
    <Compile Remove="BAL\Data\Accounts\AccountService.cs" />
    <Compile Remove="BAL\Data\Bank\BankBranchService.cs" />
    <Compile Remove="BAL\Data\Bank\BankService.cs" />
    <Compile Remove="BAL\Data\Counties\CityService.cs" />
    <Compile Remove="BAL\Data\Counties\CountryService.cs" />
    <Compile Remove="BAL\Data\Counties\DistrictService.cs" />
    <Compile Remove="BAL\Data\DealrsGroup\DealerGroupService.cs" />
    <Compile Remove="BAL\Data\Organization\BranchService.cs" />
    <Compile Remove="BAL\Data\Organization\CompanyProfileService.cs" />
    <Compile Remove="BAL\Data\Products\ProductPropertyElementService.cs" />
    <Compile Remove="BAL\Data\Products\ProductUnitService.cs" />
    <Compile Remove="BAL\Data\Products\PropertyElementService.cs" />
    <Compile Remove="BAL\Data\Products\PropertyService.cs" />
    <Compile Remove="BAL\Data\Products\RecipeService.cs" />
    <Compile Remove="BAL\Data\Products\UnitService.cs" />
    <Compile Remove="BAL\Data\Security\RoleService.cs" />
    <Compile Remove="BAL\Data\Security\ShiftService.cs" />
    <Compile Remove="BAL\Financials\FinancialInvoiceService.cs" />
    <Compile Remove="BAL\Financials\FinancialTypeService.cs" />
    <Compile Remove="BAL\Invoices\InvoiceProductService.cs" />
    <Compile Remove="BAL\Invoices\InvoiceTypeService.cs" />
    <Compile Remove="BAL\Orders\OrderProductService.cs" />
    <Compile Remove="BAL\Transactions\InventoryProductService.cs" />
    <Compile Remove="BAL\Transactions\InventoryService.cs" />
    <Compile Remove="BAL\Transactions\TransactionProductService.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.9" />
    <PackageReference Include="X.PagedList.Mvc.Core" Version="10.5.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Repository\Repository.csproj" />
    <ProjectReference Include="..\Utility\Utility.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="BAL\Data\AccountsType\" />
    <Folder Include="BAL\Data\Accounts\" />
    <Folder Include="BAL\Data\Bank\" />
    <Folder Include="BAL\Data\Counties\" />
    <Folder Include="BAL\Data\DealrsGroup\" />
  </ItemGroup>

</Project>
