<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>  
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Areas\Financials\Data\**" />
    <Compile Remove="Areas\Financials\Models\**" />
    <Compile Remove="Areas\Invoices\Data\**" />
    <Compile Remove="Areas\Invoices\Models\**" />
    <Compile Remove="Areas\Orders\Data\**" />
    <Compile Remove="Areas\Orders\Models\**" />
    <Compile Remove="Areas\Setting\Data\**" />
    <Compile Remove="Areas\Setting\Models\**" />
    <Compile Remove="Areas\Transactions\Data\**" />
    <Compile Remove="Areas\Transactions\Models\**" />
    <Compile Remove="Views\Account\**" />
    <Compile Remove="wwwroot\Assets\Revolutions\**" />
    <Content Remove="Areas\Financials\Data\**" />
    <Content Remove="Areas\Financials\Models\**" />
    <Content Remove="Areas\Invoices\Data\**" />
    <Content Remove="Areas\Invoices\Models\**" />
    <Content Remove="Areas\Orders\Data\**" />
    <Content Remove="Areas\Orders\Models\**" />
    <Content Remove="Areas\Setting\Data\**" />
    <Content Remove="Areas\Setting\Models\**" />
    <Content Remove="Areas\Transactions\Data\**" />
    <Content Remove="Areas\Transactions\Models\**" />
    <Content Remove="Views\Account\**" />
    <Content Remove="wwwroot\Assets\Revolutions\**" />
    <Content Remove="bundleconfig.json" />
    <Content Remove="Views\Home\InvoicePrint.cshtml" />
    <EmbeddedResource Remove="Areas\Financials\Data\**" />
    <EmbeddedResource Remove="Areas\Financials\Models\**" />
    <EmbeddedResource Remove="Areas\Invoices\Data\**" />
    <EmbeddedResource Remove="Areas\Invoices\Models\**" />
    <EmbeddedResource Remove="Areas\Orders\Data\**" />
    <EmbeddedResource Remove="Areas\Orders\Models\**" />
    <EmbeddedResource Remove="Areas\Setting\Data\**" />
    <EmbeddedResource Remove="Areas\Setting\Models\**" />
    <EmbeddedResource Remove="Areas\Transactions\Data\**" />
    <EmbeddedResource Remove="Areas\Transactions\Models\**" />
    <EmbeddedResource Remove="Views\Account\**" />
    <EmbeddedResource Remove="wwwroot\Assets\Revolutions\**" />
    <None Remove="Areas\Financials\Data\**" />
    <None Remove="Areas\Financials\Models\**" />
    <None Remove="Areas\Invoices\Data\**" />
    <None Remove="Areas\Invoices\Models\**" />
    <None Remove="Areas\Orders\Data\**" />
    <None Remove="Areas\Orders\Models\**" />
    <None Remove="Areas\Setting\Data\**" />
    <None Remove="Areas\Setting\Models\**" />
    <None Remove="Areas\Transactions\Data\**" />
    <None Remove="Areas\Transactions\Models\**" />
    <None Remove="Views\Account\**" />
    <None Remove="wwwroot\Assets\Revolutions\**" />    
  </ItemGroup>

  <ItemGroup>
    <None Remove="SQLFiles\DealerListSql.sql" />
    <None Remove="SQLFiles\DealersStatmentSql.sql" />
    <None Remove="SQLFiles\Test.sql" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="SQLFiles\Test.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="SQLFiles\DealersStatmentSql.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="SQLFiles\DealerListSql.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BuildBundlerMinifier" Version="3.2.449" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="3.1.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.5" />
    <PackageReference Include="PuppeteerSharp" Version="6.0.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="1.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Service\Service.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="PrintOut\" />
    <Folder Include="wwwroot\bundle\css\" />
    <Folder Include="wwwroot\bundle\js\" />
    <Folder Include="wwwroot\Files\" />    
  </ItemGroup>

  <ItemGroup>
    <None Include="bundleconfig.json" />
    <None Include="wwwroot\jquery-ui-1.13.0.custom\external\jquery\jquery.js" />
    <None Include="wwwroot\jquery-ui-1.13.0.custom\jquery-ui.js" />
    <None Include="wwwroot\jquery-ui-1.13.0.custom\jquery-ui.min.js" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Views\Home\Login.cshtml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ProjectExtensions>
    <VisualStudio>
      <UserProperties bundleconfig_1json__JsonSchema="https://www.graphql-code-generator.com/config.schema.json" />
    </VisualStudio>
  </ProjectExtensions>

</Project>