global using OrgSys.SharedKernel;
global using MasterData.Domain;
global using Organization.Domain;
global using Administration.Domain;
global using Accounting.Domain;
global using Sales.Domain;
global using Parties.Domain;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
