<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Abstraction\IAdminContext.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BuildingBlocks\OrgSys.SharedKernel\OrgSys.SharedKernel.csproj" />
    <ProjectReference Include="..\Modules\MasterData\MasterData.Domain\MasterData.Domain.csproj" />
    <ProjectReference Include="..\Modules\Organization\Organization.Domain\Organization.Domain.csproj" />
    <ProjectReference Include="..\Modules\Administration\Administration.Domain\Administration.Domain.csproj" />
    <ProjectReference Include="..\Modules\Accounting\Accounting.Domain\Accounting.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="CorePagination" Version="0.6.0" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resource\Message.Designer.Designer.cs">
      <DependentUpon>Message.Designer.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resource\Title.Designer.Designer.cs">
      <DependentUpon>Title.Designer.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resource\Message.Designer.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resource\Message.Designer.resx">
      <LastGenOutput>Message.Designer.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resource\Title.Designer.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resource\Title.Designer.resx">
      <LastGenOutput>Title.Designer.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>

</Project>
