//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message_Designer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message_Designer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utility.Resource.Message.Designer", typeof(Message_Designer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An abbreviated name of the product.
        /// </summary>
        public static string AbbreviatedNameProduct {
            get {
                return ResourceManager.GetString("AbbreviatedNameProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address is a letter number between 3 to 500.
        /// </summary>
        public static string AddressRange {
            get {
                return ResourceManager.GetString("AddressRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Required.
        /// </summary>
        public static string AddressRequired {
            get {
                return ResourceManager.GetString("AddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The barcode is a letter number between 5 to 15.
        /// </summary>
        public static string BarcodeRange {
            get {
                return ResourceManager.GetString("BarcodeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode Required.
        /// </summary>
        public static string BarcodeRequired {
            get {
                return ResourceManager.GetString("BarcodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Required.
        /// </summary>
        public static string BranchRequired {
            get {
                return ResourceManager.GetString("BranchRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification Required.
        /// </summary>
        public static string ClassificationRequired {
            get {
                return ResourceManager.GetString("ClassificationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The classification to which the product belongs.
        /// </summary>
        public static string ClassificationWhichProductBelongs {
            get {
                return ResourceManager.GetString("ClassificationWhichProductBelongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here.
        /// </summary>
        public static string ClickHere {
            get {
                return ResourceManager.GetString("ClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code is increased automatically and can be changed.
        /// </summary>
        public static string CodeIncreasedAutomaticallyCanBechanged {
            get {
                return ResourceManager.GetString("CodeIncreasedAutomaticallyCanBechanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code is a letter number between 3 to 10.
        /// </summary>
        public static string CodeRange {
            get {
                return ResourceManager.GetString("CodeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Required.
        /// </summary>
        public static string CodeRequired {
            get {
                return ResourceManager.GetString("CodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name Required.
        /// </summary>
        public static string CompanyNameRequired {
            get {
                return ResourceManager.GetString("CompanyNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password invalid.
        /// </summary>
        public static string ConfirmPasswordNotValid {
            get {
                return ResourceManager.GetString("ConfirmPasswordNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password required.
        /// </summary>
        public static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Required.
        /// </summary>
        public static string CostRequired {
            get {
                return ResourceManager.GetString("CostRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountryRequired.
        /// </summary>
        public static string CountryRequired {
            get {
                return ResourceManager.GetString("CountryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Required.
        /// </summary>
        public static string CustomerRequired {
            get {
                return ResourceManager.GetString("CustomerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Required.
        /// </summary>
        public static string DateRequired {
            get {
                return ResourceManager.GetString("DateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete confirmation.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The descriptionis a letter number between 5 to 500.
        /// </summary>
        public static string DescriptionRange {
            get {
                return ResourceManager.GetString("DescriptionRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Required.
        /// </summary>
        public static string DescriptionRequired {
            get {
                return ResourceManager.GetString("DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doublicat is UserName / Email.
        /// </summary>
        public static string DoublicatUserName {
            get {
                return ResourceManager.GetString("DoublicatUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the file?.
        /// </summary>
        public static string DoYouWantDeleteFile {
            get {
                return ResourceManager.GetString("DoYouWantDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements Under Property.
        /// </summary>
        public static string ElementsUnderProperty {
            get {
                return ResourceManager.GetString("ElementsUnderProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email format must be entered.
        /// </summary>
        public static string EmailFromate {
            get {
                return ResourceManager.GetString("EmailFromate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email exist.
        /// </summary>
        public static string EmailIsExist {
            get {
                return ResourceManager.GetString("EmailIsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email invalid.
        /// </summary>
        public static string EmailNotValid {
            get {
                return ResourceManager.GetString("EmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is a letter number between 3 to 20.
        /// </summary>
        public static string EmailRange {
            get {
                return ResourceManager.GetString("EmailRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Name.
        /// </summary>
        public static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Property Element.
        /// </summary>
        public static string EnterPropertyElement {
            get {
                return ResourceManager.GetString("EnterPropertyElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter The Quantity Please.
        /// </summary>
        public static string EnterQuantity {
            get {
                return ResourceManager.GetString("EnterQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the rate please.
        /// </summary>
        public static string EnterRate {
            get {
                return ResourceManager.GetString("EnterRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax invalid.
        /// </summary>
        public static string FaxNotValid {
            get {
                return ResourceManager.GetString("FaxNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax Required.
        /// </summary>
        public static string FaxRequired {
            get {
                return ResourceManager.GetString("FaxRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you are not redirected to the login page within 15 seconds.
        /// </summary>
        public static string IfYouAreNotRedirectedToTheLoginPageWithin15Seconds {
            get {
                return ResourceManager.GetString("IfYouAreNotRedirectedToTheLoginPageWithin15Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ingredients that the product is made of.
        /// </summary>
        public static string IngredientsThatProductMadeOf {
            get {
                return ResourceManager.GetString("IngredientsThatProductMadeOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It consists of 13 numbers.
        /// </summary>
        public static string ItConsists13Numbers {
            get {
                return ResourceManager.GetString("ItConsists13Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is a letter number between 3 to 50.
        /// </summary>
        public static string NameRange {
            get {
                return ResourceManager.GetString("NameRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Required.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality Required.
        /// </summary>
        public static string NationalityRequired {
            get {
                return ResourceManager.GetString("NationalityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The nickname is a letter number between 3 to 15.
        /// </summary>
        public static string NicknameRange {
            get {
                return ResourceManager.GetString("NicknameRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname Required.
        /// </summary>
        public static string NicknameRequired {
            get {
                return ResourceManager.GetString("NicknameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results.
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string NotMatch {
            get {
                return ResourceManager.GetString("NotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password invalid.
        /// </summary>
        public static string PasswordNotValid {
            get {
                return ResourceManager.GetString("PasswordNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Type Required.
        /// </summary>
        public static string PaymentTypeRequired {
            get {
                return ResourceManager.GetString("PaymentTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone exist.
        /// </summary>
        public static string PhoneExist {
            get {
                return ResourceManager.GetString("PhoneExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Not Valid.
        /// </summary>
        public static string PhoneNotValid {
            get {
                return ResourceManager.GetString("PhoneNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone is a letter number between 8 to 25.
        /// </summary>
        public static string PhoneRange {
            get {
                return ResourceManager.GetString("PhoneRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Required.
        /// </summary>
        public static string PhoneRequired {
            get {
                return ResourceManager.GetString("PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Required.
        /// </summary>
        public static string PriceRequired {
            get {
                return ResourceManager.GetString("PriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase price from suppliers.
        /// </summary>
        public static string PurchasePriceFromSuppliers {
            get {
                return ResourceManager.GetString("PurchasePriceFromSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put your notes on the produc.
        /// </summary>
        public static string PutYourNotesProduc {
            get {
                return ResourceManager.GetString("PutYourNotesProduc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Required.
        /// </summary>
        public static string RateRequired {
            get {
                return ResourceManager.GetString("RateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Required.
        /// </summary>
        public static string RoleRequired {
            get {
                return ResourceManager.GetString("RoleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select The Product.
        /// </summary>
        public static string SelectProduct {
            get {
                return ResourceManager.GetString("SelectProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select unit please.
        /// </summary>
        public static string SelectUnit {
            get {
                return ResourceManager.GetString("SelectUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selling price of the product.
        /// </summary>
        public static string SellingPriceProduct {
            get {
                return ResourceManager.GetString("SellingPriceProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of Company Required.
        /// </summary>
        public static string SizeOfCompanyRequired {
            get {
                return ResourceManager.GetString("SizeOfCompanyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to so please confirm that if you do not find the email in inbox, you may receive it in junk folder.
        /// </summary>
        public static string SoPleaseConfirm {
            get {
                return ResourceManager.GetString("SoPleaseConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start typing product to search....
        /// </summary>
        public static string StartSearch {
            get {
                return ResourceManager.GetString("StartSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Required.
        /// </summary>
        public static string StockRequired {
            get {
                return ResourceManager.GetString("StockRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A supplier from whom the product is purchased.
        /// </summary>
        public static string SupplierFromWhomProductPurchased {
            get {
                return ResourceManager.GetString("SupplierFromWhomProductPurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Required.
        /// </summary>
        public static string SupplierRequired {
            get {
                return ResourceManager.GetString("SupplierRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your interest in our service. To start with us in Orignizer, you must complete the registration process first according to the conditions described during the creation of the request, and then start with the trial version or the instant subscription..
        /// </summary>
        public static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Product Was Selected.
        /// </summary>
        public static string TheProductWasSelected {
            get {
                return ResourceManager.GetString("TheProductWasSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This unit has already been selected.
        /// </summary>
        public static string ThisUnitWasSelected {
            get {
                return ResourceManager.GetString("ThisUnitWasSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to complete the activation your account.
        /// </summary>
        public static string ToCompleteTheActivationYourAccount {
            get {
                return ResourceManager.GetString("ToCompleteTheActivationYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can contact technical support if there is a problem during the registration process from this email. .
        /// </summary>
        public static string ToContactTechnicalSupport {
            get {
                return ResourceManager.GetString("ToContactTechnicalSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Activity Required.
        /// </summary>
        public static string TypeActivityRequired {
            get {
                return ResourceManager.GetString("TypeActivityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Required.
        /// </summary>
        public static string UnitRequired {
            get {
                return ResourceManager.GetString("UnitRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units by which the product is measured.
        /// </summary>
        public static string UnitsWhichProductMeasured {
            get {
                return ResourceManager.GetString("UnitsWhichProductMeasured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you already have an account,.
        /// </summary>
        public static string YoHaveAccount {
            get {
                return ResourceManager.GetString("YoHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will receive an email now on.
        /// </summary>
        public static string YouWillReceiveAnEmailNowOn {
            get {
                return ResourceManager.GetString("YouWillReceiveAnEmailNowOn", resourceCulture);
            }
        }
    }
}
