<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="AuthProvider.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Core" Version="5.2.9" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.ViewFeatures" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="7.0.0-rc.2.22472.3" />
    <PackageReference Include="Microsoft.Extensions.Localization.Abstractions" Version="7.0.0-rc.2.22476.2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resource\Message.Designer.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Message.Designer.resx</DependentUpon>
    </Compile>
    <Compile Update="Resource\Title.Designer.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Title.Designer.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resource\Message.Designer.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resource\Message.Designer.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Message.Designer.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resource\Title.Designer.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resource\Title.Designer.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Title.Designer.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
