<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Repositories\**" />
    <Compile Remove="UnitOfwork\**" />
    <EmbeddedResource Remove="Repositories\**" />
    <EmbeddedResource Remove="UnitOfwork\**" />
    <None Remove="Repositories\**" />
    <None Remove="UnitOfwork\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Persistence\Data\AdminContext.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
    <ProjectReference Include="..\Repository\Repository.csproj" />
    <ProjectReference Include="..\Utility\Utility.csproj" />
  </ItemGroup>

</Project>
